import { randomBytes } from 'node:crypto';

/**
 * Ids are generated by the app, never by the UI, and they double as folder
 * names on disk. The regex is therefore deliberately strict: lowercase,
 * digits, underscore and dash only, no dots, no separators, bounded length.
 */
export const ID_PATTERN = /^[a-z][a-z0-9_-]{2,63}$/;

export type IdPrefix =
  | 'brd' | 'wrk' | 'rev' | 'dec' | 'ses' | 'mem' | 'doc' | 'gen' | 'bcp' | 'bcr'
  // Coordination (autonomous runs, schema 12): run/task/dispatch/message/ask/cost rows.
  | 'crn' | 'ctk' | 'cdp' | 'cms' | 'cak' | 'crs' | 'cld'
  // Conexiones MCP (esquema 13): una fila por cuenta con un servidor externo.
  | 'con'
  // El plantel de la marca (esquema 14): una persona que los trabajos convocan.
  | 'bm';

export function newId(prefix: IdPrefix): string {
  return `${prefix}_${randomBytes(10).toString('hex')}`;
}

export function isValidId(value: unknown): value is string {
  return typeof value === 'string' && ID_PATTERN.test(value);
}

export function nowIso(): string {
  return new Date().toISOString();
}

/** File-system friendly timestamp: 2026-09-05T14-03-22-123Z */
export function compactTimestamp(iso: string): string {
  return iso.replace(/[:.]/g, '-');
}

export function slugify(value: string, fallback = 'item'): string {
  const slug = value
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  return slug.length > 0 ? slug : fallback;
}
