import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { ensureDir, readTextIfExists, writeFileAtomic, writeImmutableFile } from '../core/atomicFile';
import { compactTimestamp } from '../core/ids';
import { LattePaths, WORK_FILES, safeJoin } from '../core/paths';
import { isManagedFile, type RenderedInstructionFile } from './instructions';

/**
 * The only two directories side files (truncated sections, skill bodies,
 * nested brand-memory copies) ever live under. `.latte/generations` is a
 * pinned receipt store: it MUST NOT appear here, because every
 * writeInstructions call deletes side-file entries that the compositor did not
 * re-request.
 */
const SIDE_FILE_DIRS = [WORK_FILES.contextDir, WORK_FILES.skillsDir];

const WORK_README = `# Latte work directory

This folder is managed by Latte (local-first Agent Marketing Platform).

- *.md             — the tracked deliverables of this work (brief.md is the
                     default one; strategy.md, calendar.md and others appear as
                     you create them). The human edits them from Latte, agents
                     edit them here. Latte re-reads a file before saving and
                     refuses to overwrite a change it has not seen.
- CLAUDE.md        — managed context for Claude Code (regenerated by Latte)
- AGENTS.md        — managed context for Codex / OpenCode (regenerated by Latte)
- .latte/snapshots — immutable snapshots taken from the app
- .claude/         — not Latte's. Claude Code writes its per-folder permissions
                     here when you answer "always" to one of its prompts, which
                     is why it stops asking. Deleting it makes it ask again.
`;

export interface DocumentOnDisk {
  content: string;
  /** ISO timestamp of the last modification, or null when the file is missing. */
  modifiedAt: string | null;
  /** Content hash. A save must present the fingerprint it started from. */
  fingerprint: string;
}

/**
 * Identifies a piece of content, not a file version: renames and atomic
 * replacements (which change inode and mtime) do not move it, and two writers
 * producing the same text do not conflict.
 */
export function fingerprintOf(content: string): string {
  return createHash('sha1').update(content, 'utf8').digest('hex').slice(0, 16);
}

/** Latte generates every document file name; user text never reaches the path. */
export function documentFileName(kind: string, used: string[]): string {
  const base = /^[a-z][a-z0-9-]{0,30}$/.test(kind) ? kind : 'document';
  let name = `${base}.md`;
  for (let n = 2; used.includes(name); n += 1) name = `${base}-${n}.md`;
  return name;
}

/**
 * Everything on disk for a work lives under one app-managed directory.
 * The class never receives user paths: only validated ids and fixed names.
 */
export class WorkspaceFiles {
  constructor(private readonly paths: LattePaths) {}

  get root(): string {
    return this.paths.root;
  }

  ensureBrand(brandId: string): string {
    const dir = this.paths.brandDir(brandId);
    ensureDir(dir);
    return dir;
  }

  ensureWork(brandId: string, workId: string, initialDocument: string): string {
    const dir = this.paths.workDir(brandId, workId);
    ensureDir(dir);
    ensureDir(this.paths.snapshotsDir(brandId, workId));
    const readme = this.paths.workFile(brandId, workId, WORK_FILES.readme);
    if (!fs.existsSync(readme)) writeFileAtomic(readme, WORK_README);
    const deliverable = this.paths.workFile(brandId, workId, WORK_FILES.brief);
    if (!fs.existsSync(deliverable)) writeFileAtomic(deliverable, initialDocument);
    return dir;
  }

  /** Points a work at a folder the user chose; every path then resolves there. */
  linkWork(workId: string, directory: string): void {
    this.paths.linkWork(workId, directory);
  }

  workDir(brandId: string, workId: string): string {
    return this.paths.workDir(brandId, workId);
  }

  readDocument(brandId: string, workId: string, fileName: string = WORK_FILES.brief): DocumentOnDisk {
    const file = this.paths.workFile(brandId, workId, fileName);
    const content = readTextIfExists(file);
    if (content === null) return { content: '', modifiedAt: null, fingerprint: fingerprintOf('') };
    return { content, modifiedAt: fs.statSync(file).mtime.toISOString(), fingerprint: fingerprintOf(content) };
  }

  writeDocument(brandId: string, workId: string, content: string, fileName: string = WORK_FILES.brief): void {
    writeFileAtomic(this.paths.workFile(brandId, workId, fileName), content);
  }

  /** Size and mtime without reading the content: used to list untracked files. */
  statDocument(brandId: string, workId: string, fileName: string): { bytes: number; modifiedAt: string | null } {
    try {
      const stat = fs.statSync(this.paths.workFile(brandId, workId, fileName));
      return { bytes: stat.size, modifiedAt: stat.mtime.toISOString() };
    } catch {
      return { bytes: 0, modifiedAt: null };
    }
  }

  documentExists(brandId: string, workId: string, fileName: string): boolean {
    return fs.existsSync(this.paths.workFile(brandId, workId, fileName));
  }

  /**
   * Writes the managed instruction files. If a user replaced one of them with
   * their own (no managed marker), it is left alone and reported: we never
   * overwrite files we do not own.
   *
   * `files` are the side files a truncated section or an enabled skill points
   * to (see instructions.ts); they always live under .latte/ and are written
   * (and stale ones removed) regardless of whether CLAUDE.md/AGENTS.md
   * themselves were skipped.
   */
  writeInstructions(
    brandId: string,
    workId: string,
    rendered: string,
    files: RenderedInstructionFile[] = [],
  ): { written: string[]; unchanged: string[]; skipped: string[]; sideFilesChanged: boolean } {
    // `written` is what actually hit the disk; `unchanged` is the managed files
    // whose text was already byte-identical (no write, no mtime change). The
    // brand-context propagation report needs that distinction: a work that did
    // not need to change is not the same as one that did.
    const written: string[] = [];
    const unchanged: string[] = [];
    const skipped: string[] = [];
    for (const name of [WORK_FILES.claude, WORK_FILES.agents]) {
      const file = this.paths.workFile(brandId, workId, name);
      const existing = readTextIfExists(file);
      if (existing !== null && !isManagedFile(existing)) {
        skipped.push(name);
        continue;
      }
      if (existing === rendered) {
        unchanged.push(name);
        continue;
      }
      writeFileAtomic(file, rendered);
      written.push(name);
    }
    const sideFilesChanged = this.syncSideFiles(brandId, workId, files);
    return { written, unchanged, skipped, sideFilesChanged };
  }

  /**
   * Latte owns .latte/context and .latte/skills entirely: every call writes
   * the current side files and removes whatever it left there before that no
   * longer applies (a decision log back under the inline ceiling, a skill
   * turned off). Compares before writing so an unchanged render touches
   * nothing, and reports whether it changed anything at all.
   */
  private syncSideFiles(brandId: string, workId: string, files: RenderedInstructionFile[]): boolean {
    const root = this.paths.workDir(brandId, workId);
    const wanted = new Map(files.map((f) => [safeJoin(root, ...f.path.split('/')), f.content]));
    let changed = false;
    for (const dirName of SIDE_FILE_DIRS) {
      const dir = safeJoin(root, WORK_FILES.metaDir, dirName);
      if (this.removeUnwantedSideFiles(dir, wanted)) changed = true;
    }
    for (const [absolute, content] of wanted) {
      if (readTextIfExists(absolute) === content) continue;
      writeFileAtomic(absolute, content);
      changed = true;
    }
    return changed;
  }

  /**
   * Recursively drops side files (and leftover empty dirs) that this render
   * did not re-request, including nested brand-memory copies. Returns true
   * when something was removed.
   */
  private removeUnwantedSideFiles(dir: string, wanted: Map<string, string>): boolean {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return false;
    }
    let changed = false;
    for (const entry of entries) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (this.removeUnwantedSideFiles(absolute, wanted)) changed = true;
        try {
          if (fs.readdirSync(absolute).length === 0) { fs.rmdirSync(absolute); changed = true; }
        } catch { /* already gone or not empty */ }
      } else if (!wanted.has(absolute)) {
        fs.rmSync(absolute, { force: true });
        changed = true;
      }
    }
    return changed;
  }

  writeSnapshot(brandId: string, workId: string, revisionId: string, createdAt: string, content: string): string {
    const fileName = `${compactTimestamp(createdAt)}-${revisionId}.md`;
    const file = this.paths.snapshotFile(brandId, workId, fileName);
    writeImmutableFile(file, content);
    return file;
  }

  listSnapshotFiles(brandId: string, workId: string): string[] {
    const dir = this.paths.snapshotsDir(brandId, workId);
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir).filter((f) => f.endsWith('.md')).sort();
  }
}
