import type { BackendApi } from '../services/latteService';

/**
 * Single source of truth for the IPC surface: exactly the LatteAPI methods
 * from shared/contracts.ts. The preload (plain CJS, no imports) repeats this
 * list; tests/backend/ipc.test.ts asserts they match.
 */
export const API_METHODS = [
  'getUiLocale',
  'setUiLocale',
  'getContentLocale',
  'setContentLocale',
  'appInfo',
  'listBrands',
  'createBrand',
  'updateBrand',
  'readAgencyProfile',
  'saveAgencyProfile',
  'importBrandKit',
  'publishBrandKit',
  'revokeBrandKit',
  'importAgencyKit',
  'publishAgencyKit',
  'setWorkBrandChoice',
  'readWorkBrandContext',
  'listWorks',
  'createWork',
  'updateWork',
  'prepareGeneration',
  'saveBrief',
  'listRevisions',
  'snapshot',
  'listDocuments',
  'readDocument',
  'documentState',
  'createDocument',
  'saveDocument',
  'updateDocument',
  'snapshotDocument',
  'keepDraftAsVersion',
  'listDocumentRevisions',
  'exportDocument',
  'listUntrackedFiles',
  'listFolderEntries',
  'listDeliverables',
  'openDeliverable',
  'revealDeliverable',
  'copyDeliverable',
  'revealWorkFolder',
  'importFiles',
  'listHandoffs',
  'dismissHandoff',
  'listSkills',
  'setSkillEnabled',
  'listSkillCandidates',
  'approveSkillCandidate',
  'rejectSkillCandidate',
  'promoteSkillCandidate',
  'applyFunnelProposal',
  'dismissFunnelProposal',
  'getWorkPermissions',
  'setWorkPermissions',
  'trackFile',
  'saveAsDocument',
  'acknowledgeBase',
  'useFolder',
  'listDecisions',
  'addDecision',
  'getDecisionAuthority','setDecisionAuthority','approveDecision','rejectDecision','archiveDecision',
  'runtimeStatus',
  'startAgent',
  'writeAgent',
  'resizeAgent',
  'stopAgent',
  'readMemory',
  'saveMemory',
  'exportWork',
  'chatStatus',
  'startChat',
  'listChatMessages',
  'sendChat',
  'abortChat',
  'stopChat',
  'replyPermission',
  'replyQuestion',
  'listProviders',
  'connectProviderKey',
  'disconnectProvider',
  'startProviderOAuth',
  'completeProviderOAuth',
  'getPrimaryAgent',
  'setPrimaryAgent',
  'listAgentRuntimes',
  'listMcpServers',
  'addMcpServer',
  'removeMcpServer',
  'addAgentAccount',
  'removeAgentAccount',
  'startAccountLogin',
  'logoutAccount',
  'listAccountModels',
  'setTeamMemberModel',
  'setTeamMemberTier',
  'listRoles',
  'listProfiles',
  'saveProfile',
  'listTeam',
  'addTeamMember',
  'openTeamMember',
  'pauseTeamMember',
  'finishTeamMember',
  'restartTeamMember',
  'removeTeamMember',
  'draftContinuation',
] as const satisfies readonly (keyof BackendApi)[];

export type ApiMethod = (typeof API_METHODS)[number];

// Compile-time exhaustiveness: every BackendApi method must be listed.
type MissingMethods = Exclude<keyof BackendApi, ApiMethod>;
const assertAllMethodsListed: MissingMethods extends never ? true : never = true;
void assertAllMethodsListed;

/** Maximum positional arguments per method; extra arguments are rejected. */
export const API_ARITY: Record<ApiMethod, number> = {
  getUiLocale: 0,
  setUiLocale: 1,
  getContentLocale: 0,
  setContentLocale: 1,
  appInfo: 0,
  listBrands: 0,
  createBrand: 1,
  updateBrand: 2,
  readAgencyProfile: 0,
  saveAgencyProfile: 2,
  importBrandKit: 1,
  publishBrandKit: 2,
  revokeBrandKit: 3,
  importAgencyKit: 0,
  publishAgencyKit: 1,
  setWorkBrandChoice: 3,
  readWorkBrandContext: 1,
  listWorks: 1,
  createWork: 2,
  updateWork: 2,
  prepareGeneration: 1,
  saveBrief: 3,
  listRevisions: 1,
  snapshot: 1,
  listDocuments: 1,
  readDocument: 1,
  documentState: 1,
  createDocument: 4,
  saveDocument: 3,
  updateDocument: 2,
  snapshotDocument: 1,
  keepDraftAsVersion: 2,
  listDocumentRevisions: 1,
  exportDocument: 1,
  listUntrackedFiles: 1,
  listFolderEntries: 1,
  listDeliverables: 1,
  openDeliverable: 2,
  revealDeliverable: 2,
  copyDeliverable: 2,
  revealWorkFolder: 1,
  importFiles: 1,
  listHandoffs: 1,
  dismissHandoff: 2,
  listSkills: 0,
  setSkillEnabled: 2,
  listSkillCandidates: 0,
  approveSkillCandidate: 1,
  rejectSkillCandidate: 1,
  promoteSkillCandidate: 1,
  applyFunnelProposal: 1,
  dismissFunnelProposal: 1,
  getWorkPermissions: 1,
  setWorkPermissions: 2,
  trackFile: 2,
  saveAsDocument: 4,
  acknowledgeBase: 1,
  useFolder: 1,
  listDecisions: 1,
  addDecision: 2,
  getDecisionAuthority:1,setDecisionAuthority:2,approveDecision:2,rejectDecision:1,archiveDecision:1,
  runtimeStatus: 0,
  startAgent: 2,
  writeAgent: 2,
  resizeAgent: 3,
  stopAgent: 1,
  readMemory: 1,
  saveMemory: 2,
  exportWork: 1,
  chatStatus: 0,
  startChat: 4,
  listChatMessages: 1,
  sendChat: 2,
  abortChat: 1,
  stopChat: 1,
  replyPermission: 3,
  replyQuestion: 3,
  listProviders: 0,
  connectProviderKey: 2,
  disconnectProvider: 1,
  startProviderOAuth: 3,
  completeProviderOAuth: 3,
  getPrimaryAgent: 0,
  setPrimaryAgent: 1,
  listAgentRuntimes: 0,
  listMcpServers: 1,
  addMcpServer: 2,
  removeMcpServer: 2,
  addAgentAccount: 2,
  removeAgentAccount: 2,
  startAccountLogin: 2,
  logoutAccount: 2,
  listAccountModels: 2,
  setTeamMemberModel: 2,
  setTeamMemberTier: 2,
  listRoles: 0,
  listProfiles: 0,
  saveProfile: 2,
  listTeam: 1,
  addTeamMember: 3,
  openTeamMember: 1,
  pauseTeamMember: 1,
  finishTeamMember: 1,
  restartTeamMember: 1,
  removeTeamMember: 1,
  draftContinuation: 1,
};

export const CHANNEL_PREFIX = 'latte:';
export const AGENT_EVENT_CHANNEL = 'latte:agent-event';
export const CHAT_EVENT_CHANNEL = 'latte:chat-event';

/**
 * Updates live outside API_METHODS on purpose: they are not backend
 * operations. They need the app itself (quit, install, native dialogs), so
 * they are their own small surface with the same envelope and the same sender
 * check as everything else. The preload repeats these names literally.
 */
export const UPDATE_STATE_CHANNEL = 'latte:update-state';
export const UPDATE_CHECK_CHANNEL = 'latte:update-check';
export const UPDATE_DOWNLOAD_CHANNEL = 'latte:update-download';
export const UPDATE_INSTALL_CHANNEL = 'latte:update-install';
export const UPDATE_CHANNELS = [UPDATE_CHECK_CHANNEL, UPDATE_DOWNLOAD_CHANNEL, UPDATE_INSTALL_CHANNEL] as const;

export function channelFor(method: ApiMethod): string {
  return `${CHANNEL_PREFIX}${method}`;
}

export type IpcEnvelope<T> =
  | { ok: true; value: T }
  | { ok: false; code: string; message: string };
