import type { BackendApi } from '../services/latteService';

/**
 * Single source of truth for the IPC surface: exactly the LatteAPI methods
 * from shared/contracts.ts. The preload (plain CJS, no imports) repeats this
 * list; tests/backend/ipc.test.ts asserts they match.
 */
export const API_METHODS = [
  'getUiLocale',
  'setUiLocale',
  'getContentLocale',
  'setContentLocale',
  'getOnboardingComplete',
  'setOnboardingComplete',
  'getOnboardingDraft',
  'setOnboardingDraft',
  'clearOnboardingDraft',
  'appInfo',
  'featureFlags',
  'listBrands',
  'getBrand',
  'createBrand',
  'updateBrand',
  'archiveBrand',
  'restoreBrand',
  'listArchivedBrands',
  'readAgencyProfile',
  'saveAgencyProfile',
  'importBrandKit',
  'publishBrandKit',
  'revokeBrandKit',
  'importAgencyKit',
  'publishAgencyKit',
  'setWorkBrandChoice',
  'readWorkBrandContext',
  'readBrandIdentity','addBrandIdentityFiles','removeBrandIdentityFile','approveBrandIdentity','revokeBrandIdentity','requestBrandIdentityExtraction',
  'listWorks',
  'createWork',
  'updateWork',
  'prepareGeneration',
  'saveBrief',
  'listRevisions',
  'snapshot',
  'listDocuments',
  'listBrandDocuments',
  'readDocument',
  'documentState',
  'createDocument',
  'saveDocument',
  'updateDocument',
  'snapshotDocument',
  'keepDraftAsVersion',
  'listDocumentRevisions',
  'exportDocument',
  'listUntrackedFiles',
  'listFolderEntries',
  'listDeliverables',
  'openDeliverable',
  'revealDeliverable',
  'copyDeliverable',
  'revealWorkFolder',
  'importFiles',
  'listHandoffs',
  'dismissHandoff',
  'listSkills',
  'setSkillEnabled',
  'listSkillCandidates',
  'approveSkillCandidate',
  'rejectSkillCandidate',
  'promoteSkillCandidate',
  'applyFunnelProposal',
  'dismissFunnelProposal',
  'toggleOutOfScopeStage',
  'getWorkPermissions',
  'setWorkPermissions',
  'trackFile',
  'saveAsDocument',
  'acknowledgeBase',
  'useFolder',
  'listDecisions',
  'listBrandDecisions',
  'addDecision',
  'getDecisionAuthority','setDecisionAuthority','approveDecision','rejectDecision','archiveDecision',
  'listBrandContextProposals','saveBrandContext','clearBrandContext','approveBrandContextProposal','rejectBrandContextProposal','requestBrandContextDraft','brandContextStatus','listBrandContextRevisions','restoreBrandContextRevision',
  'getCoordinationAuthority','setCoordinationAuthority','getCoordinationReview','setCoordinationReview','getCoordinationBudget','setCoordinationBudget','getCoordinatorGrant','setCoordinatorGrant',
  'startCoordinationRun','pauseCoordinationRun','resumeCoordinationRun','cancelCoordinationRun','getCoordinationRun','listCoordinationGates','resolveCoordinationGate','listCoordinationLog','listOpenCoordinationAsks','answerCoordinationAsk','acceptHandoffAsTask','settleCoordinationDispatch',
  'coordinationRuntimeSupport','listActiveCoordinationRuns','getCoordinationEnabled','setCoordinationEnabled','getCoordinationGlobalBudget','setCoordinationGlobalBudget','markCoordinationSeen','listCoordinationHires','listCoordinationTasks','listCoordinationMessages',
  'runtimeStatus',
  'startAgent',
  'writeAgent',
  'resizeAgent',
  'stopAgent',
  'readMemory',
  'saveMemory',
  'exportWork',
  'chatStatus',
  'startChat',
  'listChatMessages',
  'sendChat',
  'abortChat',
  'stopChat',
  'replyPermission',
  'replyQuestion',
  'listProviders',
  'connectProviderKey',
  'disconnectProvider',
  'startProviderOAuth',
  'completeProviderOAuth',
  'getPrimaryAgent',
  'setPrimaryAgent',
  'listAgentRuntimes',
  'listMcpServers',
  'removeMcpServer',
  'listConnections',
  'listAllConnections',
  'connectConnection',
  'reconnectConnection',
  'disconnectConnection',
  'deleteConnection',
  'listImportableConnections',
  'addAgentAccount',
  'removeAgentAccount',
  'startAccountLogin',
  'logoutAccount',
  'listAccountModels',
  'getAcpTierModels',
  'setAcpTierModel',
  'setTeamMemberModel',
  'setTeamMemberTier',
  'listRoles',
  'listProfiles',
  'saveProfile',
  'setRoleAvatar',
  'listTeam',
  'addTeamMember',
  'openTeamMember',
  'pauseTeamMember',
  'finishTeamMember',
  'restartTeamMember',
  'removeTeamMember',
  'listBrandTeam',
  'addBrandMember',
  'retireBrandMember',
  'setBrandCoordinator',
  'callUpMember',
  'draftContinuation',
] as const satisfies readonly (keyof BackendApi)[];

export type ApiMethod = (typeof API_METHODS)[number];

// Compile-time exhaustiveness: every BackendApi method must be listed.
type MissingMethods = Exclude<keyof BackendApi, ApiMethod>;
const assertAllMethodsListed: MissingMethods extends never ? true : never = true;
void assertAllMethodsListed;

/** Maximum positional arguments per method; extra arguments are rejected. */
export const API_ARITY: Record<ApiMethod, number> = {
  getUiLocale: 0,
  setUiLocale: 1,
  getContentLocale: 0,
  setContentLocale: 1,
  getOnboardingComplete: 0,
  setOnboardingComplete: 1,
  getOnboardingDraft: 0,
  setOnboardingDraft: 1,
  clearOnboardingDraft: 0,
  appInfo: 0,
  featureFlags: 0,
  listBrands: 0,
  getBrand: 1,
  createBrand: 1,
  updateBrand: 2,
  archiveBrand: 1,
  restoreBrand: 1,
  listArchivedBrands: 0,
  readAgencyProfile: 0,
  saveAgencyProfile: 2,
  importBrandKit: 1,
  publishBrandKit: 2,
  revokeBrandKit: 3,
  importAgencyKit: 0,
  publishAgencyKit: 1,
  setWorkBrandChoice: 3,
  readWorkBrandContext: 1,
  readBrandIdentity: 1, addBrandIdentityFiles: 1, removeBrandIdentityFile: 2, approveBrandIdentity: 1, revokeBrandIdentity: 1, requestBrandIdentityExtraction: 1,
  listWorks: 1,
  createWork: 2,
  updateWork: 2,
  prepareGeneration: 1,
  saveBrief: 3,
  listRevisions: 1,
  snapshot: 1,
  listDocuments: 1,
  listBrandDocuments: 1,
  readDocument: 1,
  documentState: 1,
  createDocument: 4,
  saveDocument: 3,
  updateDocument: 2,
  snapshotDocument: 1,
  keepDraftAsVersion: 2,
  listDocumentRevisions: 1,
  exportDocument: 1,
  listUntrackedFiles: 1,
  listFolderEntries: 1,
  listDeliverables: 1,
  openDeliverable: 2,
  revealDeliverable: 2,
  copyDeliverable: 2,
  revealWorkFolder: 1,
  importFiles: 1,
  listHandoffs: 1,
  dismissHandoff: 2,
  listSkills: 0,
  setSkillEnabled: 2,
  listSkillCandidates: 0,
  approveSkillCandidate: 1,
  rejectSkillCandidate: 1,
  promoteSkillCandidate: 1,
  applyFunnelProposal: 1,
  dismissFunnelProposal: 1,
  toggleOutOfScopeStage: 2,
  getWorkPermissions: 1,
  setWorkPermissions: 2,
  trackFile: 2,
  saveAsDocument: 4,
  acknowledgeBase: 1,
  useFolder: 1,
  listDecisions: 1,
  listBrandDecisions: 1,
  addDecision: 2,
  getDecisionAuthority:1,setDecisionAuthority:2,approveDecision:2,rejectDecision:1,archiveDecision:1,
  listBrandContextProposals:1,saveBrandContext:3,clearBrandContext:2,approveBrandContextProposal:3,rejectBrandContextProposal:1,requestBrandContextDraft:1,brandContextStatus:1,listBrandContextRevisions:1,restoreBrandContextRevision:3,
  getCoordinationAuthority:1,setCoordinationAuthority:2,getCoordinationReview:1,setCoordinationReview:2,getCoordinationBudget:1,setCoordinationBudget:2,getCoordinatorGrant:1,setCoordinatorGrant:2,
  startCoordinationRun:1,pauseCoordinationRun:1,resumeCoordinationRun:1,cancelCoordinationRun:1,getCoordinationRun:1,listCoordinationGates:1,resolveCoordinationGate:3,listCoordinationLog:1,listOpenCoordinationAsks:1,answerCoordinationAsk:2,acceptHandoffAsTask:2,settleCoordinationDispatch:4,
  coordinationRuntimeSupport:1,listActiveCoordinationRuns:0,getCoordinationEnabled:0,setCoordinationEnabled:1,getCoordinationGlobalBudget:0,setCoordinationGlobalBudget:1,markCoordinationSeen:1,listCoordinationHires:1,listCoordinationTasks:1,listCoordinationMessages:1,
  runtimeStatus: 0,
  startAgent: 2,
  writeAgent: 2,
  resizeAgent: 3,
  stopAgent: 1,
  readMemory: 1,
  saveMemory: 2,
  exportWork: 1,
  chatStatus: 0,
  startChat: 4,
  listChatMessages: 1,
  sendChat: 2,
  abortChat: 1,
  stopChat: 1,
  replyPermission: 3,
  replyQuestion: 3,
  listProviders: 0,
  connectProviderKey: 2,
  disconnectProvider: 1,
  startProviderOAuth: 3,
  completeProviderOAuth: 3,
  getPrimaryAgent: 0,
  setPrimaryAgent: 1,
  listAgentRuntimes: 0,
  listMcpServers: 1,
  removeMcpServer: 2,
  listConnections: 1,
  listAllConnections: 0,
  connectConnection: 1,
  reconnectConnection: 1,
  disconnectConnection: 1,
  deleteConnection: 1,
  listImportableConnections: 0,
  addAgentAccount: 2,
  removeAgentAccount: 2,
  startAccountLogin: 2,
  logoutAccount: 2,
  listAccountModels: 2,
  getAcpTierModels: 0,
  setAcpTierModel: 3,
  setTeamMemberModel: 2,
  setTeamMemberTier: 2,
  listRoles: 0,
  listProfiles: 0,
  saveProfile: 2,
  setRoleAvatar: 2,
  listTeam: 1,
  addTeamMember: 3,
  openTeamMember: 1,
  pauseTeamMember: 1,
  finishTeamMember: 1,
  restartTeamMember: 1,
  removeTeamMember: 1,
  listBrandTeam: 1,
  addBrandMember: 3,
  retireBrandMember: 1,
  setBrandCoordinator: 2,
  callUpMember: 2,
  draftContinuation: 1,
};

export const CHANNEL_PREFIX = 'latte:';
export const AGENT_EVENT_CHANNEL = 'latte:agent-event';
export const CHAT_EVENT_CHANNEL = 'latte:chat-event';
/** sdd/autonomous-coordination, task 6.37: a run/task/dispatch/gate change, so the renderer can route an event from a Brand the person is not looking at. */
export const COORDINATION_EVENT_CHANNEL = 'latte:coordination-event';

/**
 * Updates live outside API_METHODS on purpose: they are not backend
 * operations. They need the app itself (quit, install, native dialogs), so
 * they are their own small surface with the same envelope and the same sender
 * check as everything else. The preload repeats these names literally.
 */
export const UPDATE_STATE_CHANNEL = 'latte:update-state';
export const UPDATE_CHECK_CHANNEL = 'latte:update-check';
export const UPDATE_DOWNLOAD_CHANNEL = 'latte:update-download';
export const UPDATE_INSTALL_CHANNEL = 'latte:update-install';
export const UPDATE_CHANNELS = [UPDATE_CHECK_CHANNEL, UPDATE_DOWNLOAD_CHANNEL, UPDATE_INSTALL_CHANNEL] as const;

export function channelFor(method: ApiMethod): string {
  return `${CHANNEL_PREFIX}${method}`;
}

export type IpcEnvelope<T> =
  | { ok: true; value: T }
  | { ok: false; code: string; message: string };
